# 基础服务配置信息
server:
  port: 8020

spring:
  application:
    name: base-service

---
# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# 增加关于RabbitMQ的连接和用户信息
rabbitmq:
  host: ${rabbitmq.host}
  port: ${rabbitmq.port}
  username: ${rabbitmq.username}
  password: ${rabbitmq.password}