
# bootstrap.yml 先于 application.yml 加载；所以配置服务要先加载，否则报错
# 增加关于RabbitMQ的连接和用户信息
rabbitmq:
  host: ${rabbitmq.host}
  port: ${rabbitmq.port}
  username: ${rabbitmq.username}
  password: ${rabbitmq.password}